### ISSUE TITLE
Mangles UTF-8 strings

### ISSUE THREAD

**Issue by kyrias** [clehner/nij#2]
Turns `"Löthberg"` into `"LC6thberg"` when editing and saving.

What's weird is that `ö` is `U+00F6`, so I'm not sure how it turned it into `C6`.

**Comment by kyrias** [comment]
Seems in UTF-8 `ö` is `0xC3 0xB6`, so maybe that's why.

**Comment by clehner** [comment]
It was using ascii encoding. I changed it now to use utf8. Does that work?

**Comment by kyrias** [comment]
Indeed it does. That's a weird way for it to fail though, hmm.

**Comment by kyrias** [comment]
(And thanks for the quick fix.)

**Comment by clehner** [comment]
Sure thing; thanks for reporting.
